VALIDATION_PROMPT_TEMPLATE = """You are an expert Quality Assurance (QA) and Style-Matching assistant. Your mission is to receive a "User Query" and an "Initial Answer" generated by another system.

You must follow these steps precisely:
1.  **Double-Check:** Review the "Initial Answer" to ensure it is factually correct, accurate, complete, and directly answers the "User Query".
2.  **Identify Errors:** If you find any errors (factual, grammatical, or logical) or **dangerous medical advice**, correct them.
3.  **Analyze Style:** Carefully analyze the "User Query" to determine its style (e.g., tone, level of formality, slang/formal language, sentence length).
4.  **Refine & Rephrase:** Rework the corrected answer. Make it clearer, more concise (if possible), and ensure it flows naturally.
5.  **Match Style:** The final answer you provide MUST perfectly match the style and tone of the original "User Query".

### INPUTS ###

[User Query]:
{user_query}

[Initial Answer]:
{answer}

### OUTPUT ###
Return ONLY the final, refined, and style-matched answer. Do not include any preambles or explanations (e.g., "Here is the revised answer:").
"""


def Post_Query_Validate(Model , user_query: str, answer: str) -> str:
    """
    Validates, corrects, and style-matches an answer using a validation model.
    """ 
    
    try:
        final_prompt = VALIDATION_PROMPT_TEMPLATE.format(
            user_query=user_query,
            answer=answer
        )
    except Exception as e:
        print(f"CRITICAL: Error formatting prompt: {e}. Returning original answer.")
        return answer

    try:
        raw_response_content = Model(final_prompt) 

        if not raw_response_content:
            print("Warning: Validation model returned None or empty. Using original answer.")
            return answer
        
        rewritten_answer = raw_response_content.strip().strip('"')

        if not rewritten_answer or len(rewritten_answer) < 10:
            print("Warning: Rewritten answer extraction failed or was too short. Using original answer.")
            return answer
        else:
            print("INFO: Answer successfully rewritten and validated.")
            return rewritten_answer

    except Exception as e:
        print(f"CRITICAL: Error during answer rewriting process: {e}. Returning original answer.")
        return answer